on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: yarn
    - run: yarn test:e2e:ci
      env:
        CYPRESS_RUN_KEY: ${{ secrets.CYPRESS_RUN_KEY }}
